services:
  - type: web
    name: clantrust
    env: node
    rootDir: ClanTrust
    buildCommand: npm --prefix ClanTrust ci && npm --prefix ClanTrust run build
    startCommand: npm --prefix ClanTrust run start
    postDeployCommand: npm --prefix ClanTrust run db:deploy
